baseURL = ""
languageCode = "en"
title = "Gr√©goire Boiron"
enableRobotsTXT=true
googleAnalytics="UA-148345166-2"
EnableMissingTranslationPlaceholders=true
disqusShortname = "graygzou-blog"
summaryLength = 20
log=true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[build]
  useResourceCacheWhen = "fallback"
  writeStats = false